openapi: 3.0.0
info:
  title: Easyappz API
  version: '1.0.0'
  description: |
    Current public endpoints. Models are defined in Mongoose under server/src/models.
servers:
  - url: /api
paths:
  /hello:
    get:
      summary: Health hello endpoint
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required: [message]
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required: [error]
  /status:
    get:
      summary: Service status
      responses:
        '200':
          description: Status info
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ok]
                  timestamp:
                    type: string
                    format: date-time
                required: [status, timestamp]
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required: [error]
